name: Workflow Practice

on:
    pull_request:
        types: [ opened ]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "hello Github"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Output PWD
        run: |
          ls
          echo pwd