name: Workflow Practice

on: [ pull_request ]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "hello Github"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: Create artifact
        run: cd ./project && zip -r project.zip .
        uses: actions/upload-artifact@v2
          with:
            retention-days: 1